// Automatically generated by SUtools, editing not advised.
#ifndef R_LARS_H
#define R_LARS_H
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(String) dgettext ("lars", String)
#else
#define _(String) (String)
#endif


#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}
void F77_SUB(delcol)(
double *r,
int *ip,
int *k,
double *z,
int *n,
int *nz
);
 
static R_NativePrimitiveArgType delcol_t[] = {
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP
};

static R_FortranMethodDef fMethods[] = {
FDEF(delcol) ,
{NULL, NULL, 0}
};

void R_init_lars(DllInfo *dll){
  R_registerRoutines(dll, NULL, NULL, fMethods, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
#endif
